In [8]:
# 1
import numpy as np

A = np.array([1, 0] * 32)
C = A.reshape((8, 8))
for i in range(0, 7, 2):
    C[i] = C[i][::-1]
print(C)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [9]:
# 2

A = np.array([np.arange(0,5)] * 5)
print(A)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [10]:
# 3

A = np.random.random(27).reshape(3,3,3)
print(A)

[[[0.95157236 0.03456997 0.99294949]
  [0.88110594 0.28803397 0.72182942]
  [0.93021124 0.38633475 0.09173111]]

 [[0.08794363 0.45985902 0.51914515]
  [0.56210172 0.16625533 0.60715568]
  [0.12515303 0.35686919 0.73415195]]

 [[0.43458709 0.66617888 0.35272663]
  [0.68664785 0.00602222 0.09912707]
  [0.51045313 0.90677647 0.78403453]]]


In [11]:
# 4

A = np.array([0] * 25).reshape(5,5)
for i in range(5):
    for j in range(5):
        if (i == 0 or j == 0 or i == 4 or j == 4):
            A[i][j] = 1

print(A)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [12]:
# 5

A = np.array([2,5,7,3234,64,234,7589,34523,324,64])
A = np.sort(A)[::-1]
print(A)


[34523  7589  3234   324   234    64    64     7     5     2]


In [13]:
# 6

A = np.arange(25).reshape(5,5)
print("form:", A.shape)
print("size:", A.size)
print("dim:",  A.ndim)

form: (5, 5)
size: 25
dim: 2


In [14]:
# 7
import pandas as pd

a = pd.Series([5,7])
b = pd.Series([8,11])

e = np.sqrt((a[0] - b[0]) ** 2 + (a[1] - b[1]) ** 2)

print(e)


5.0


In [15]:
# 8

url = 'https://raw.githubusercontent.com/akmand/datasets/main/baseball.csv'
dataframe = pd.read_csv(url)
print(dataframe.head(5))


       1      2    3    4   5  6   7    8   9   10  11  12  13  14  15  16  \
0  0.271  0.328   74  161  22  6  12   58  49  133  23  17   1   1   0   0   
1  0.264  0.318   24   48   7  0   1   22  15   18   0   7   0   0   0   0   
2  0.251  0.338  101  141  35  3  32  105  71  104  34   6   0   0   1   0   
3  0.224  0.274   28   94  21  1   1   44  27   54   2   7   1   1   0   0   
4  0.206  0.262   14   51  18  1   1   28  17   26   0   3   1   1   0   0   

   salary  
0     109  
1     160  
2    2700  
3     550  
4     300  


In [16]:
# 9

url = 'https://raw.githubusercontent.com/akmand/datasets/main/baseball.csv'
dataframe = pd.read_csv(url)

print("1.1)Первые пять строк:")
print(dataframe.head(5), '\n')
print("1.2)Последние пять строк:")
print(dataframe.tail(5), '\n')
print("1.3)Количество строк и столбцов:")
print(dataframe.shape, '\n')
print("1.4)Описательная статистика:")
print(dataframe.describe(), '\n')
print("2)Срез данных (3 - 6):")
print(dataframe.iloc[3:7], '\n')
print("3)Срез данных (salary < 200):")
print(dataframe[dataframe['salary'] < 200].head(10), '\n')


1.1)Первые пять строк:
       1      2    3    4   5  6   7    8   9   10  11  12  13  14  15  16  \
0  0.271  0.328   74  161  22  6  12   58  49  133  23  17   1   1   0   0   
1  0.264  0.318   24   48   7  0   1   22  15   18   0   7   0   0   0   0   
2  0.251  0.338  101  141  35  3  32  105  71  104  34   6   0   0   1   0   
3  0.224  0.274   28   94  21  1   1   44  27   54   2   7   1   1   0   0   
4  0.206  0.262   14   51  18  1   1   28  17   26   0   3   1   1   0   0   

   salary  
0     109  
1     160  
2    2700  
3     550  
4     300   

1.2)Последние пять строк:
         1      2   3    4   5  6   7   8   9   10  11  12  13  14  15  16  \
332  0.269  0.303  32   58  12  1  13  33  11   51   1   2   0   0   0   0   
333  0.288  0.366  24   47   7  0   7  24  18   23   2   3   0   0   0   0   
334  0.208  0.265  12   35  11  1   0  15  14   30   2   6   0   0   0   0   
335  0.290  0.349  59  141  30  2  16  64  42  102  14   6   1   0   0   0   
336  0.225  0.312 

In [17]:
# 10
from sklearn import preprocessing

url = "https://raw.githubusercontent.com/akmand/datasets/master/iris.csv"
dataframe = pd.read_csv(url)

print(dataframe.head(10), '\n')

scaler = preprocessing.MinMaxScaler()
dataframe['sepal_length_cm'] = scaler.fit_transform(dataframe[['sepal_length_cm']])
dataframe['sepal_width_cm'] = (dataframe['sepal_width_cm'] - dataframe['sepal_width_cm'].mean()) / dataframe['sepal_width_cm'].std()
print(dataframe.head(10))

   sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0              5.1             3.5              1.4             0.2  setosa
1              4.9             3.0              1.4             0.2  setosa
2              4.7             3.2              1.3             0.2  setosa
3              4.6             3.1              1.5             0.2  setosa
4              5.0             3.6              1.4             0.2  setosa
5              5.4             3.9              1.7             0.4  setosa
6              4.6             3.4              1.4             0.3  setosa
7              5.0             3.4              1.5             0.2  setosa
8              4.4             2.9              1.4             0.2  setosa
9              4.9             3.1              1.5             0.1  setosa 

   sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0         0.222222        1.028611              1.4             0.2  setosa
1         